# Generated by Django 5.1.4 on 2025-01-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator'), ('jury', 'Jury')], default='jury', max_length=20),
        ),
    ]
